### ISSUE TITLE
Remove the PC

### ISSUE THREAD

**Issue by tustin2121** [tustin2121/trihard-emerald#32]
All PC terminals in the game should be ~~removed entirely~~ made inoperable. (Barring the secret base PC.) This means doing the following:

- [x] #3 - Access to the Storage system is gone.
- [x] Access to the player's computer is gone, meaning that we should expand the player's backpack to compensate.
- [x] Access to the player's mailbox is gone, meaning that mail that is being removed should always return to the bag.
- [x] Access to the Pokedex evaluation is gone, and nothing of value was lost.
- [x] Access to the hall of fame is gone, and nothing of value was lost.
- [ ] Add custom events to Pokemon Center PCs, like the ones listed below (still need Fallarbor, Verdanturf, Pokemon League, and Pacifidlog)

And, because trolling chat is fun, the PC's will still be present in the world, but each will have a different event attached to them instead of the PC event.
- When the PC is used, a dialog box simply says: "There's a sign on the PC that says "Out of Order" with a frowny face."
- One PC is always being used by an NPC on video chat. "Yes, mom... No, mom... Yes, mom..." [turns to player] "Excuse me, some privacy please?"
- One PC is also being used by an NPC. "Just five more minutes. Someone is wrong on the internet and I need to correct them."
- "There's a music video playing on loop: A man is dancing and singing about how he intends to never give up on someone,`\l`nor let them down,`\l`nor run them around`\n`and desert them."
- *[pc turn on sound]* "[Name] turned on the PC." "It says "No Keyboard detected. Press F1 to continue."" *[pc turn off sound]*
- "[Name] tries to turn on the PC." "Seems to be unplugged."
- "The screen is all blue, and there's random text all over the screen."
- NPC: "Wait your turn."
- NPC lass at the PC: "Stop it and leave.`\p`Now. Get out." A random youngster NPC some distance away: "That girl by the PC is so mean... *sniffle*"
- NPC: "What do you kids do to these PCs?! I haven't seen one working PC in this entire region!" [turns to pc] "*BANG!* Work you stupid thing!"
- One PC has a screen that looks like the evil PC emote when the map loads. When the player moves closer to it, there's a line of event triggers which will fire which turn the screen normal, in such a way where the screen should turn normal the moment it slides on screen. Interacting with the PC yields "...Is... is that faint laughter...?" A random NPC across the room will ask "I think I'm seeing things... Is it just me, or did that PC have a face...?" (which then resets the above). This should be the Mauville center's PC.
- The PC in the player's room: "There's a live stream where a whole bunch of people are controlling a single video game by typing in chat... welp, time to get going."
- etc.

**Comment by m4-used-rollout** [comment]
On the Out of Order PC: "It looks like someone tried to pull the power supply out."

![image](https://user-images.githubusercontent.com/1911304/56868250-684cd500-69df-11e9-92a7-b630ea897383.png)
![image](https://user-images.githubusercontent.com/1911304/56868252-73a00080-69df-11e9-9c9f-de3bb58db16b.png)

**Comment by tustin2121** [comment]
Moved remaining items to #93.
