### ISSUE TITLE
Running Shoes always available

### ISSUE THREAD

**Issue by tustin2121** [tustin2121/trihard-emerald#38]
It's a flag that should just be set at the start of the game. No point in having it in the story.

**Comment by huderlem** [comment]
This implies that the event where the Mom gives running shoes to the player should be removed.  Is that the case?  Also, should running shoes be usable literally everywhere (indoors, etc.)?

**Comment by tustin2121** [comment]
The event where Mom gives us the running shoes will be replaced with an event where Dad doesn't give us running shoes but still meets us outside; don't remove the old event, please, I'd like it as a base to work off of next milestone when all the story changes start going in.

Having them work everywhere, even indoors, would be nice to have for the player, so I wouldn't mind that happening.

**Comment by tustin2121** [comment]
Turns out this was already done for a while now. Instead of the flag about the running shoes being given, it's a system flag about the B button allowing you to run.
