### ISSUE TITLE
"Run" is "Forfeit"

### ISSUE THREAD

**Issue by tustin2121** [tustin2121/trihard-emerald#74]
Make it possible to forfeit a trainer battle, making "Run" into "Forfeit". 

* The confirmation dialog reads "What are you, a coward?" [No!/Yeah...]
	* For TPP, this is locked off behind a dialog "You're not a coward, are you?" for most of the story.
* After the Lilycove Logan battle where Logan says "you're allowed to forfeit, you know" (or the final Logan Battle if they skip Lilycove), this changes to "Concede?"
	* For TPP, this is still locked behind a dialog "No matter what Logan says, quitting is for losers..."
* When this is selected, the battle is lost and the player whites out. The whiteout cutscene may change to reflect the concession.

**Comment by m4-used-rollout** [comment]
What is this for?

**Comment by tustin2121** [comment]
For the L TriHard R E. Hence the labels.
